
Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '='

Timestamp: 2024-09-23 03:23:11.390154

Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '='

Timestamp: 2024-09-23 03:23:11.390319

Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '<'

Timestamp: 2024-09-23 03:23:11.463372

Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '<'

Timestamp: 2024-09-23 03:23:11.463439

Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '<'

Timestamp: 2024-09-23 03:23:11.534826

Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '<'

Timestamp: 2024-09-23 03:23:11.534909

Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '<'

Timestamp: 2024-09-23 03:23:11.606773

Status: FAILED!
Reason: Unable to run guess.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/9780357881019-fundamentals-of-python-3e-f96bb60d-efd0-481d-b048-94bb43750b4d/python/chapter3/ex03/guess.py", line 13, in <module>
    userNumber = int(input("Enter your number: "))
ValueError: invalid literal for int() with base 10: '<'

Timestamp: 2024-09-23 03:23:11.606841
